import { Car } from './lib/types';

export const mockCars: Car[] = [
  {
    id: 1,
    brand: 'Toyota',
    model: 'Camry',
    year: 2019,
    mileage: 91000,
    price: 1520000,
    average_price: 1892500,
    deviation_percent: -19.69,
    status: 'underpriced',
    region: 'Москва',
    url: 'https://bankrot.example/lots/camry-2019-1',
    image_url: '',
    premium_only: false,
  },
  {
    id: 2,
    brand: 'BMW',
    model: 'X5',
    year: 2018,
    mileage: 120000,
    price: 2850000,
    average_price: 3282222,
    deviation_percent: -13.17,
    status: 'underpriced',
    region: 'Санкт-Петербург',
    url: 'https://bankrot.example/lots/bmw-x5-2018-1',
    image_url: '',
    premium_only: false,
  },
  {
    id: 3,
    brand: 'Lada',
    model: 'Vesta',
    year: 2021,
    mileage: 47000,
    price: 880000,
    average_price: 978750,
    deviation_percent: -10.09,
    status: 'underpriced',
    region: 'Татарстан',
    url: 'https://bankrot.example/lots/vesta-2021-1',
    image_url: '',
    premium_only: false,
  },
  {
    id: 4,
    brand: 'Kia',
    model: 'Sportage',
    year: 2020,
    mileage: 68000,
    price: 1710000,
    average_price: 1845000,
    deviation_percent: -7.32,
    status: 'underpriced',
    region: 'Краснодар',
    url: 'https://bankrot.example/lots/sportage-2020-1',
    image_url: '',
    premium_only: false,
  },
  {
    id: 5,
    brand: 'Hyundai',
    model: 'Solaris',
    year: 2021,
    mileage: 54000,
    price: 980000,
    average_price: 1035000,
    deviation_percent: -5.31,
    status: 'underpriced',
    region: 'Екатеринбург',
    url: 'https://bankrot.example/lots/solaris-2021-1',
    image_url: '',
    premium_only: false,
  },
];
